
[pumpkin_carving]
	#Allows custom carved pumpkins to be placed by villagers and appear in abandoned farm structure
	custom_carvings = true
	#Pumpkin carving mode
	#Allowed Values: NONE, BOTH, GUI, MANUAL
	pumpkin_carve_mode = "BOTH"
	#Jack o Lantern carving mode
	#Allowed Values: NONE, BOTH, GUI, MANUAL
	jack_o_lantern_carve_mode = "NONE"

[halloween_start]
	#Day from which villagers will start placing pumpkins & trick or treating
	#Range: 1 ~ 12
	month = 10
	#Day from which villagers will start placing pumpkins & trick or treating
	#Range: 1 ~ 31
	day = 20

[halloween_end]
	#Day from which villagers will start removing placed pumpkins
	#Range: 1 ~ 12
	month = 11
	#Day from which villagers will start removing placed pumpkins
	#Range: 1 ~ 31
	day = 10

[trick_or_treating]
	#Nota that all these configs will not take effect until the game is reloaded
	#Time of day at which baby villagers will start trick-or-treating
	#Range: 0 ~ 24000
	start_time = 12000
	#Time of day at which baby villagers will stop trick-or-treating. Note that this will only properly work if it's at night since baby villagers can only trick or treat during their sleep schedule which is from 12000 to 0
	#Range: 0 ~ 24000
	end_time = 0

[season_mod_compat]
	#Enables compatibility with Serene Seasons (Forge) or Fabric Seasons (Fabric). Only takes effect if the mod is installed. Will make autumn season only active during certain seasons. Note that this will override previous time window settings
	enabled = true
	#Season in which the mod villager AI behaviors will be active
	winter_season_sub_seasons = ["MID_AUTUMN", "LATE_AUTUMN"]

