
["Possibility of Actions"]
	canCatLeap = false
	canCrawl = true
	#Possibility to Frontward-Dodge By double tapping a button
	canFrontDodgeByDoubleTapping = false
	canDodge = true
	canFastRunning = true
	canClingToCliff = true
	canRoll = true
	canVault = true
	canWallJump = true
	canDive = true
	canFlipping = true
	canBreakFall = true
	canWallSlide = true
	canHorizontalWallRun = true

["Modifier Values"]
	#FastRun Speed Modifier
	#Range: 0.001 ~ 4.5
	fastRunModifier = 1.0

["Stamina HUD Configuration"]
	#hide stamina HUD when Stamina is infinite
	hideS_HUD = false
	#use Light Stamina HUD
	useLightHUD = true
	#horizontal alignment
	#Allowed Values: Left, Right
	align_H_S_HUD = "Right"
	#vertical alignment
	#Allowed Values: Top, Bottom
	align_V_S_HUD = "Bottom"
	#horizontal margin
	#Range: 0 ~ 100
	margin_H_S_HUD = 3
	#vertical margin
	#Range: 0 ~ 100
	margin_V_S_HUD = 3
	#vertical offset of light stamina HUD
	#Range: -50 ~ 50
	offset_V_LS_HUD = 0

["Other Configuration"]
	#Auto turning forward when WallJump
	autoTurningWallJump = false
	#Disable WallJump toward a wall
	disableWallJumpTowardWall = true
	#Disable Roll rotation of camera
	disableCameraRotationRolling = false
	#Disable Flipping rotation of camera
	disableCameraRotationFlipping = false
	#Disable Double-Tapping For Dodge. Please Use Dodge Key instead
	disableDoubleTapping = false
	#Disable Crawl in air (experimental)
	disableCrawlInAir = false
	#Enable Roll While player is in creative mode (experimental)
	enableRollCreative = false
	#Make Vault Need Vault Key Pressed
	vaultNeedKeyPressed = true
	#enable players to do actions needing Fast-Running by sprint
	replaceSprintWithFastRun = true
	#Substitute a sprint of vanilla for the FastRunning
	substituteSprint = true
	#Infinite Stamina(this needs a permission from server, even if it is on single player's game)
	#Please check 'parcool-server.toml' in 'serverconfig' directory
	infiniteStamina = false

#Stamina Section may be affected by Server config
[Stamina]
	#ParCool consume hanger value instead of stamina
	useHangerInstead = true
	#Range: 300 ~ 10000
	MaxValueOfStamina = 1200

	[Stamina.Consumption]
		#Range: 0 ~ 10000
		Breakfall = 100
		#Range: 0 ~ 10000
		CatLeap = 300
		#Range: 0 ~ 10000
		ClingToCliff = 2
		#Range: 0 ~ 10000
		ClimbUp = 100
		#Range: 0 ~ 10000
		Dodge = 80
		#Range: 0 ~ 10000
		FastRunning = 4
		#Range: 0 ~ 10000
		Flipping = 80
		#Range: 0 ~ 10000
		Vault = 50
		#Range: 0 ~ 10000
		WallJump = 120

	#About ParCool
	[Stamina.ParCool]
		#ParCool is Active
		ParCool_Activation = true

